pytorch_metric_learning.trainers.MetricLossOnly
---

---
models: models
optimizers: 
batch_size: 
loss_funcs: 
dataset: 
mining_funcs: 
iterations_per_epoch: 
data_device: 
dtype: 
loss_weights: 
sampler: 
collate_fn: 
lr_schedulers: 
gradient_clippers: 
freeze_these: 
freeze_trunk_batchnorm: 
label_hierarchy_level: 
dataloader_num_workers: 
data_and_label_getter: 
dataset_labels: 
set_min_label_to_zero: 
end_of_iteration_hook: 
end_of_epoch_hook: 
