fp16:
  enabled: True
zero_optimization:
  stage: 2
  offload_optimizer:
    device: "cpu"
  contiguous_gradients: True
  overlap_comm: True
gradient_accumulation_steps: 4
train_batch_size: 32
gradient_clipping: 1.0
