trl.SFTTrainer
---

---
model: "facebook/opt-350m"
args: training["config"]
data_collator: 
train_dataset: dataset
eval_dataset: 
processing_class: 
compute_loss_func: 
compute_metrics: 
callbacks: [loss_callback]
optimizers: 
optimizer_cls_and_kwargs: 
preprocess_logits_for_metrics: 
peft_config: 
formatting_func: 
