dataset_setup["dataset"].map
---

---
function: dataset_setup["tokenize_function"]
with_indices: 
with_rank: 
input_columns: 
batched: 
batch_size: 
drop_last_batch: 
remove_columns: 
keep_in_memory: 
load_from_cache_file: 
cache_file_names: 
writer_batch_size: 
features: 
disable_nullable: 
fn_kwargs: 
num_proc: 
desc: 
